feat(react-ts): change tsconfig module from esnext to commonjs (#1955)
`projen new react-ts --projenrc-ts` create the project but when we need compile to change some configuration gives a error like that

```bash
╰─ pj                                                                                  
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
(node:23404) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/dev/new-projen-react/.projenrc.ts:1
import { web } from "projen";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module.m._compile (/dev/new-projen-react/node_modules/ts-node/src/index.ts:1597:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/dev/new-projen-react/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at phase4 (/home/marcio/marciocadev/aaa/node_modules/ts-node/src/bin.ts:579:12)
👾 Synthesis failed: Task "default" failed when executing "ts-node --project tsconfig.dev.json .projenrc.ts" (cwd: /dev/new-projen-react)
```

To correct that I change the configuration of `ReactTypeScriptProject` setting `tsconfig.module` from `esnext` to `commonjs`

Fixes #1954 
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.