fix(upgrade-dependencies): upgrade command doesn't consider requested types (#2835)
Given 

```ts
depsUpgradeOptions: {
  types: [DependencyType.PEER],
}
```

Would produce:

```console
npm-check-updates --dep peer --upgrade --target=minor
yarn upgrade
```

However, when `yarn upgrade` executes, the peer deps aren't upgraded because peer dependencies aren't installed by default. This causes [failures](https://github.com/cdk8s-team/cdk8s-hasura/actions/runs/5698912124/job/15447288139?pr=177) such as:

```console
build » compile | jsii --silence-warnings=reserved-word
Error: Error: Declared dependency on version ^2.24.0 of cdk[8](https://github.com/cdk8s-team/cdk8s-hasura/actions/runs/5698912124/job/15447288139?pr=177#step:5:9)s, but version 2.23.0 was found
```

Projen actually automatically adds peer dependencies as dev dependencies as well. This means we need to also produce: 

```console
npm-check-updates --dep dev --upgrade --target=minor --filter {peers}
```

Also, `yarn upgrade` is not the right command to run here because it will upgrade ALL transitive dependencies, instead of just for peers. What we need is `yarn upgrade {peers}`.


---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.