docs: add maven as a tool dependency (#625)
The `build` task invokes `jsii-pacmak`, which requires Maven to be installed.

```shell
🤖 build » package | jsii-pacmak
[jsii-pacmak] [WARN] Exception occurred, not cleaning up /tmp/npm-packCWZNJH
Error: All attempts failed. Last error: Command (mvn --quiet --batch-mode deploy -D=altDeploymentRepository=local::default::file:///tmp/npm-packf4q1cq --settings=user.xml) failed with status 127:
#STDERR> /bin/sh: mvn: command not found
#STDERR>
#STDOUT>
    at retry (/Users/aisamu/code/node/projen/node_modules/jsii-pacmak/lib/util.js:70:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
🤖 Task "build » package" failed when executing "jsii-pacmak" (cwd: /Users/aisamu/code/node/projen)
error Command failed with exit code 1.
```
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.