feat(inventory): Add overrides flag
I had some challanges to create external project types with my own default values. As an example I would like to create **MyAwsCdkTypeScriptApp** that is extending **AwsCdkTypeScriptApp** with some custom logic as well as my own opiniated default values.

I first tried to use the [Omit Utility Type](https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys)

```typescript
interface MyAwsCdkTypeScriptAppOptions
        extends Omit<AwsCdkTypeScriptAppOptions, "fieldIwantToOverride">
{
        /**
         * default "myowndefaultvalue"
         */
        readonly fieldIwantToOverride: string
}

class MyAwsCdkTypeScriptApp extends AwsCdkTypeScriptApp {
        ...
        constructor(options: MyAwsCdkTypeScriptAppOptions)
        ...
}
```

Unfortunetely, JSII currently does not support that. Then I tried directly adding the field in my custom interface

```typescript
interface MyAwsCdkTypeScriptAppOptions
        extends AwsCdkTypeScriptAppOptions
{
        readonly fieldIwantToOverride: string
}

class MyAwsCdkTypeScriptApp extends AwsCdkTypeScriptApp {
        ...
        constructor(options: MyAwsCdkTypeScriptAppOptions)
        ...
}
```

JSII does not complain here as long as I keep everything about the property the same, but then this time Projen complains with the following error

```
Error: duplicate option "fieldIwantToOverride" in MyAwsCdkTypeScriptAppOptions (already declared in GitHubProjectOptions)
```

This PR changes the logic that inventory.ts uses for duplicates. I added a new directive called @overrides. If projen encounters 2 parameters with the same name, instead of generating an error, it honors the one with the **@overrides** flag.

This will only be used to create external project types, therefore I don't expect to have multiple @overrides directives for a type.