chore: pwd artifact for release (#1389)
Same as https://github.com/projen/projen/pull/1384, but for the release workflow. 

Should free the release which is currently [failing](https://github.com/projen/projen/runs/4644112485?check_suite_focus=true):

```console
Run npx projen package:js
npx: installed 65 in 5.454s
Unknown command: package:js
Error: Process completed with exit code 1.
```

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.